/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mygames;

import java.io.File;
import java.io.IOException;
import javax.sound.sampled.*;

/**
 *
 * @author Administrator
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */ private Clip clip;
        private boolean isMuted = false;
     
    public MainMenu() {
        initComponents();
        setResizable(false);
        playMusic("src\\mygames\\SFX\\INTRO.wav");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        play_button = new javax.swing.JButton();
        quit_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        mute = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        play_button.setBackground(new java.awt.Color(153, 204, 255));
        play_button.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        play_button.setForeground(new java.awt.Color(255, 255, 255));
        play_button.setText("PLAY");
        play_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        play_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(play_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 110, 50));

        quit_button.setBackground(new java.awt.Color(153, 204, 255));
        quit_button.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        quit_button.setForeground(new java.awt.Color(255, 255, 255));
        quit_button.setText("QUIT");
        quit_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(quit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 110, 50));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mygames/TITENGLOGO.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 290, 280));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Press Start 2P", 0, 14)); // NOI18N
        jLabel3.setText("WHAT AM I ?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 40));

        mute.setBackground(new java.awt.Color(153, 204, 255));
        mute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mygames/imgbuttons/volume.png"))); // NOI18N
        mute.setText("jButton1");
        mute.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muteActionPerformed(evt);
            }
        });
        getContentPane().add(mute, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mygames/javabg.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 510, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
      private void playMusic(String filepath) {
        if (!isMuted) { // Only play music if not muted
            try {
                File file = new File(filepath);
                AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(file);
                clip = AudioSystem.getClip(); // Assign to the class-level clip object
                clip.open(audioInputStream);
                clip.start();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void stopMusic() {
        if (clip != null && clip.isRunning()) {
            clip.stop();
            clip.close();
        }
    }
    
private void toggleMusic() {
    if (isMuted) {
        isMuted = false; // Unmute
        playMusic("src\\mygames\\SFX\\INTRO.wav");
    } else {
        isMuted = true; // Mute
        stopMusic();
    }
}


            
    private void play_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play_buttonActionPerformed
        playMusic("src\\mygames\\SFX\\click.wav");
        categories categoriesFrame = new categories();
        categoriesFrame.setVisible(true);
        stopMusic();
        this.dispose();  
    }//GEN-LAST:event_play_buttonActionPerformed

    private void quit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quit_buttonActionPerformed
        playMusic("src\\mygames\\SFX\\click.wav");
        this.dispose(); 
        stopMusic();
    }//GEN-LAST:event_quit_buttonActionPerformed

    private void muteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muteActionPerformed

        clip.close();
        toggleMusic();
    }//GEN-LAST:event_muteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mute;
    private javax.swing.JButton play_button;
    private javax.swing.JButton quit_button;
    // End of variables declaration//GEN-END:variables
}
